-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3307
-- Generation Time: Jun 13, 2024 at 07:34 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pwa_vijesti`
--
CREATE DATABASE IF NOT EXISTS `pwa_vijesti` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `pwa_vijesti`;

-- --------------------------------------------------------

--
-- Table structure for table `korisnik`
--

CREATE TABLE `korisnik` (
  `id` int(11) NOT NULL,
  `ime` varchar(50) NOT NULL,
  `prezime` varchar(50) NOT NULL,
  `korisnicko_ime` varchar(50) NOT NULL,
  `lozinka` varchar(255) NOT NULL,
  `razina` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `korisnik`
--

INSERT INTO `korisnik` (`id`, `ime`, `prezime`, `korisnicko_ime`, `lozinka`, `razina`) VALUES
(2, 'ante', 'antic', 'admin', '$2y$10$E7j7shW/qZqKdIdV6A6caeDImHEUm.blwtXE4kvqnqNPOHdRag4Yi', 1),
(9, 'Ivan', 'Horvat', 'horvat', '$2y$10$CYNnJr/h4hHGzy3l2pnayOZ0fA8qb5VuGmRTbqgtkCnpct2HivQG2', 0);

-- --------------------------------------------------------

--
-- Table structure for table `vijesti`
--

CREATE TABLE `vijesti` (
  `id` int(11) NOT NULL,
  `datum` varchar(25) NOT NULL,
  `naslov` varchar(255) NOT NULL,
  `sazetak` text NOT NULL,
  `tekst` text NOT NULL,
  `slika` varchar(255) DEFAULT NULL,
  `kategorija` varchar(50) NOT NULL,
  `arhiva` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `vijesti`
--

INSERT INTO `vijesti` (`id`, `datum`, `naslov`, `sazetak`, `tekst`, `slika`, `kategorija`, `arhiva`) VALUES
(13, '13.06.2024 14:46', 'Abbey Road', 'The Beatles ponovno je u centru pažnje zbog impresivnog uspjeha na tržištu.', 'Album \"Abbey Road\" The Beatlesa, koji je originalno objavljen 1969. godine, ponovno je postao hit nakon što je oborio prodajne rekorde na globalnom tržištu glazbe. Ovaj kultni album, često smatran jednim od najboljih u povijesti rock glazbe, nedavno je doživio novi val popularnosti među ljubiteljima glazbe diljem svijeta. Prodaja fizičkih kopija albuma dramatično je porasla u proteklih nekoliko mjeseci, što je dovelo do njegovog povratka na vrhove glazbenih ljestvica.\r\n\r\n\"Abbey Road\" je poznat po ikoničnoj naslovnoj fotografiji koja prikazuje članove benda kako prelaze pješački prijelaz ispred studija Abbey Road u Londonu. Album sadrži neke od najvećih hitova benda kao što su \"Come Together\", \"Something\", \"Here Comes the Sun\" i \"Octopus\'s Garden\". Kritičari su istaknuli da je album i dalje svjež i inspirativan te da je njegova glazba i dalje relevantna i danas, više od pola stoljeća nakon prvog objavljivanja.\r\n', 'abbey_road.jpg', 'kultura', 1),
(14, '13.06.2024 14:55', 'Stihovi Luke Paljetka odjekuju', 'Paljetkovi vječni stihovi svoje su mjesto pronašli u \"Ekvilibrij\" i \"Sarabanda za Anamariju\" ', 'Barda hrvatske poetike prisjetili smo se na predstavljanju grafičkih mapa u Nacionalnoj i sveučilišnoj knjižnici.\r\n\r\n- Nastojao sam postići balans između forme i antiforme sa svrhom da bih postigao taj likovni ekvilibrij, a naravno i nekakav svoj unutarnji emotivni balans, istaknuo je akademski slikar i grafičar Tin Samaržija.\r\n\r\nKolekcionar i nakladnik Božo Biškupić Samardžiju smatra vrlo talentiranim mladim grafičarom:\r\n\r\n- Zbog toga sam mu ukazao povjerenje da surađujemo s vrlo velikim hrvatskim pjesnikom Lukom Paljetkom. On je napravio 10-ak grafičkih ploča za knjigu koju je Paljetak posvetio svojoj supruzi Anamariji, rekao je Biškupić.', 'luka.jpg', 'kultura', 1),
(15, '13.06.2024 14:57', 'Cijene ulaznica rastu', 'Filmovi po prvi put u povijesti dosegli vrhunac po zaradi i ulaganjima.', 'Za prosječnog gledatelja odlazak u kino nekad je bio pristupačan i ugodan izlazak, no rast cijena karata sve više dovodi u pitanje tu percepciju. Tradicionalno, kino je bilo prostor za zajedničko iskustvo, gdje su ljudi mogli uživati u novim filmskim ostvarenjima bez ozbiljnog financijskog opterećenja. Međutim, s rastom cijena, kino postaje luksuzniji izbor koji zahtijeva pažljivo planiranje budžeta.\r\n\r\nRazlozi iza rasta cijena\r\nGlavni razlozi za rast cijena karata za filmove su mnogobrojni. Prvo, filmski studiji sve više ulažu u visokobudžetne projekte s ciljem privlačenja široke publike i postizanja visokih prihoda na početku prikazivanja. Ovo povećava troškove distribucije filmova, što se onda prenosi na cijene ulaznica kako bi se nadoknadili troškovi produkcije.\r\n\r\nTakođer, tehnološki napredak u kinematografiji, kao što su 3D projekcije i Dolby Atmos zvuk, donosi dodatne troškove, koje kina prenose na gledatelje kroz veće cijene ulaznica.\r\n\r\nReakcija gledatelja i industrije\r\nS rastom cijena karata, gledatelji postaju sve selektivniji u odabiru filmova koje će gledati u kinu. Veći broj ljudi razmatra alternativne opcije kao što su streaming platforme ili čekanje da filmovi postanu dostupni za kućnu distribuciju, gdje je cijena gledanja filmova znatno niža u usporedbi s kinom.\r\n\r\nIndustrija se suočava s izazovom prilagodbe ovim promjenama u potrošačkim navikama. Kako bi privukla publiku, kina i filmski studiji često nude različite vrste popusta, posebne ponude i programiranje filmova koji ciljaju specifične demografske skupine.\r\n\r\nKulturni i ekonomski utjecaj\r\nRast cijena karata za filmove ne samo da utječe na gledateljsko iskustvo, već ima i širi kulturni i ekonomski utjecaj. Kino je dugo bio ključni dio popularne kulture, ali je sve manje dostupan široj populaciji, posebno obiteljima i mladima. Ovo može imati dugoročne posljedice na način na koji ljudi doživljavaju i konzumiraju filmsku umjetnost.', 'cinestar.jpg', 'kultura', 1),
(16, '13.06.2024 15:00', 'Russel Crowe - Gladiator 2', 'Glumac Russel Crowe ponovno se iskušao u glumi gladijatora', 'povijesni spektakl Ridleyja Scotta iz 2000. s Russellom Croweom, Joaquinom Phoenixom, Connie Nielsen, Djimonom Hounsouom, Derekom Jacobijem i Richardom Harrisom. Crowe glumi generala Maksima Decidija Meridija (Maximus Decimus Meridius), prijatelja cara Marka Aurelija, kojeg izdaje i ubija njegov ambiciozni sin Komod (Phoenix). Zarobljen i porobljen na granicama Rimskog Carstva, Maksim se probija kroz gladijatorsku arenu kako bi osvetio ubojstvo svoje obitelji i svog cara.\r\n\r\nFilm je osvojio pet Oscara, uključujući nagradu za najbolji film. Pomogao je oživljavanju žanra povijesnog spektakla, s kasnijim filmovima kao što su Troja, Aleksandar, 300 i Scottovo Kraljevstvo nebesko.', 'gladijator.jpeg', 'kultura', 0),
(17, '13.06.2024 15:03', 'Lektira koja se ne zaboravlja', 'Sjećate li se lektire \"Vlak u snijegu\". Idalje je jedna od popularnijih knjiga za djecu.', 'Vlak u snijegu poznato je djelo hrvatskog književnika Mate Lovraka koji je najveću popularnost stekao zahvaljujući dječjim romanima od kojih je drugi, no ne i manje popularan, Družba Pere Kvržice. Radi se o slavnim djelima prema čijem su sadržaju 1970. godine snimljeni popularni filmovi. Iako je Vlak u snijegu dječji roman, obilje pouka koje u njima pronalazimo može koristiti i odraslima jer djeca ponekad imaju najbolja rješenja za svakodnevne probleme.\r\n\r\nOd samog početka ova krasna priča daje naznake zanimljivog štiva koje će svaki čitatelj pročitati s oduševljenjem čak i ako je upoznat s radnjom djela prije čitanja. Upoznavanje ove prekrasne družine i okoline u kojoj provode najviše vremena ukazuje na njihove karakterne raznolikosti. Neki od njih su radišni i marljivi, a neki su spori ili lijeni, ali svi čine jednu cjelinu koja je savršeno funkcionira. Želja za vlasti i mogućnostima koje ona pruža prožeta je dozom zavisti tako da neki od likova ne prezaju ni pred podmićivanjem kako bi li se domogli prestižne pozicije.\r\n\r\nVeć u ranoj dobi na vidjelo izlaze negativne karakterne osobne nekih likova, samo što se te negativnosti u dječjem svijetu ispravljaju bezbolnije i pravednije nego u realnosti. Djeca su iskrena i u toj iskrenosti znaju nanositi bol jedni drugima, ali sve to služi tome da se kasnije istakne pozitivni završetak.\r\n\r\nSvi odnosi i konflikti među malim zadrugarima naslijeđeni su od sredine u kojoj žive. Svaki pojedini lik može se poistovjetiti sa svojim roditeljem, bio on slabijeg ili boljeg imovinskog stanja. Oni siromašniji u djelu se uvijek pokazuju kao pošteniji jer su ono što posjeduju stekli teškim i požrtvovnim radom, stoga znaju cijeniti svaki uspjeh, bio on njihov i tuđi. Oni drugi, koji su svoj imetak stekli nasljeđivanjem, smatraju svoju privilegiju pravom te misle da se zbog njihove moći drugi moraju podvrgavati njihovim željama i potrebama.\r\n\r\nDjeca takve probleme rješavaju otvoreno, bez obzira na moguće posljedice. Problematične pojedince izoliraju tako dugo dok oni sami ne uvide svoje greške te zamole za oprost. Nekada se dogodi da sve eskalira u fizički obračun, ali drugi dan sve se brzo zaboravi – to su ipak djeca.', 'vlak.jpeg', 'kultura', 0),
(18, '13.06.2024 15:06', 'Kylian Mbappe seli u Madrid', 'Završena je jedna od najdužih transfer saga. Kylian Mbappe stavio je potpis na ugovor s Realom.\r\n', 'Mbappe je ranije objavio kako neće produžiti suradnju s PSG-om i samo se čekala potvrda imena novog kluba. Real Madrid je tu imao daleko najviše šanse i na kraju je taj \"brak\" i potvrđen.\r\n\r\nMbappe je stavio potpis na petogodišnji ugovor s Real Madridom, a ono što Parižane najviše boli je da je Mbappe čekao kraj ugovora i otišao kao slobodan igrač.\r\n\r\nZov Real Madrida bio je prejak i Mbappe je dosta ranije donio odluku kako će preseliti na Santiago Bernabeu.\r\n\r\nMbappeu je Real Madrid treći profesionalni klub u karijeri, krenuo je u Monacu još dok je tamo bio Danijel Subašić, posljednjih sedam godina dao je PSG-u, a sada seli u Real Madrid.', 'mbappe.jpg', 'sport', 0),
(19, '13.06.2024 15:07', 'Preminuo veliki Jerry West', 'Tužna vijest stiže iz Los Angelesa, preminuo je veliki Jerry West', 'Preminuo je mirno, uz njega je bila njegova supruga Karen, objavila je kalifornijska franšiza ne otkrivajući uzroke njegove smrti.\r\n\r\n\"Bio je oličenje košarkaške izvrsnosti i prijatelj svima koji su ga poznavali,\" navode Clippersi.\r\n\r\nWest je osvojio devet NBA naslova kao igrač, skaut, trener, izvršni direktor i konzultant tijekom legendarne karijere koja je trajala osam desetljeća.\r\n\r\nPod nadimkom \"Mr. Clutch\", West je bio All-Star tijekom svake sezone svoje 14-godišnje igračke karijere za Los Angeles Lakerse, pomažući klubu da osvoji naslov 1971/72.\r\n\r\nWest je proglašen MVP-jem NBA finala 1969. unatoč tome što je igrao u poraženoj momčadi. Postigao je 42 poena u sedmoj utakmici, no Lakersi su poraženi od rivala Boston Celticsa.\r\n\r\n\"Jerry West bio je košarkaški genije i figura koja je definirala našu ligu više od 60 godina. Istaknuo se ne samo kao NBA prvak i All-Star u svih 14 svojih igračkih sezona, već i kao vrhunski natjecatelj koji je prihvatio najveće trenutke,\" objavio je povjerenik NBA lige Adam Silver.\r\n\r\nKarijeru je završio s prosjekom od preko 27 poena po utakmici, u vrijeme kada šut za tri poena nije postojao. Nakon umirovljenja kao igrač 1974., trenirao je Lakerse od 1976. do 1979., a zatim je ušao u upravu i postao generalni menadžer od 1982. iduća dva desetljeća, tijekom koji su Lakersi osvojili 8 naslova između 1980. i 2002. Bio je i jedan od ključnih ljudi u formiranju tandema Shaquille O\'Neal - Kobe Bryant.\r\n\r\nPotom se pridružio Golden State Warriorsima kao član upravnog odbora (2011-2017.) s kojima je osvojio dva NBA naslova, a zatim Clippersima 2017. godine.\r\n\r\nUšao je u Kuću slavnih kao igrač 1980. i ponovno 30 godina kasnije kao član američkog olimpijskog tima 1960. Zanimljivo, West je bio inspiracija za siluetu NBA loga', 'nba.jpg', 'sport', 0),
(20, '13.06.2024 15:08', 'Jokić će igrat za Srbiju', 'Izbornik Svetislav Pešić objavio je popis od 16 igrača koji će kandidirati za Olimpijske igre.', 'Srbija će na predstojećim Olimpijskim igrama u Parizu dobiti veliko pojačanje u vidu Nikole Jokića. Potvrdio je to izbornik Svetislav Pešić koji ga je uvrstio na popis putnika za Francusku.\r\n\r\nIgraj na košarkaške utakmice na SuperSport.hr (18+ Igraj odgovorno)\r\n\r\nSrbija će prve provjere za Pariz imati 5. i 7. srpnja iza zatvorenih vratra protiv Nizozemske i Turske. Službenu prijateljsku utakimcu igrat će 12. srpnja protiv Francuske, nakon toga će u Abu Dhabiju igrati protiv Australije i SAD-a.\r\n\r\n21. srpnja igrat će protiv Japana u Beogradskoj areni, a prema Francuskoj idu tri dana kasnije.\r\n\r\nMVP NBA lige preskočio je zadnje Svjetsko prvenstvo na kojem je Srbija igrala finale, a zadnji put je igrao na Eurobasketu prije dvije godine kad su ispali u osmini finala od Italije.\r\n\r\nPopis igrača: Vasilije Micić, Aleksej Pokuševski, Bogdan Bogdanović, Nikola Jović, Nikola Jokić, Vladimir Lučić, Marko Gudurić, Vanja Marinković, Ognjen Dobrić, Filip Petrušev, Nikola Milutinov, Dušan Ristić, Aleksa Avramović, Ognjen Jaramaz, Dejan Davidovac, Uroš Plavšić.', 'jokic.jpg', 'sport', 0),
(21, '13.06.2024 15:10', 'Zaigrani Yamal', 'Barcelonino čudo od 16-godišnji krilni napadač već je dogurao i do španjolske reprezentacije.', 'S 15 godina, 9 mjeseci i 16 dana debitirao je 29. travnja 2023. za Barcelonu zamijenivši Gavija u 83. minuti utakmice La Lige protiv Betisa koji je poražen 4:0.[2] Tada je postao najmlađi igrač u klupskoj povijesti. Te je sezone s Barcelonom osvojio La Ligu.[3]\r\n\r\nPrvi puta je bio dio početne postave Barcelone 20. kolovoza 2023. kada je Barcelona pobijedila Cádiz 2:0. Tada je imao 16 godina i 38 dana te je postao najmlađi igrač u klupskoj povijesti koji je bio dio početne postave kluba u La Ligi.[4][5] U idućem susretu bio je proglašen igračem utakmice nakon što je dvaput bio asistent u ligaškom susretu protiv Villarreala koji je poražen 4:3.[6][7] Tada, 28. kolovoza, sa 16 godina i 45 dana, postao je najmlađi asistent u povijesti La Lige.[8] U tom mjesecu je postao igračem mjeseca La Lige do 23 godine.[9] Utakmicom protiv Antwerpa koji je 19. rujna poražen 5:0, Yamal je sa 16 godina i 68 dana postao drugi najmlađi debitant u povijesti UEFA Lige prvaka nakon Youssoufe Moukokoua.', 'yamal.jpg', 'sport', 1),
(22, '13.06.2024 15:14', 'Petar Pan', 'Lik Petra Pana prvi put se pojavljuje u romanu Jamesa Matthewa Barriea ', 'Gospođa i gospodin Darling imali su troje djece: djevojčicu Wendy i dječake Johna i Michaela. Bili su dobri roditelji, a imali su i \"dadilju\", kuju Nanu, koja se izvrsno brinula o djeci.\r\n\r\nAli jedne večeri gospođa Darling je uspavala djecu i upalila im noćne svjetiljke pa su gospođa i gospodin Darling otišli na zabavu, a Nana je bila vezana u dvorištu. I tako su djeca bila sama kući. Kad su zaspala, u sobu su ušli vila Zvončica i Petar Pan. Djeca su se probudila i upoznala se s nepozvanim gostima. I tako su saznali da je Petar pobjegao od roditelja jer nije želio odrasti. Uz pomoć vilinskog praha djeca su odletjela s novim prijateljima na izmišljeni otok.Tamo upoznaju Izgubljene dječake i Indijance plemena Vučje Jabučice koju je Petar spasio,bore se s gusarima i otimaju im brod nakon što su svi poraženi...Poletjeli su tim brodom i zabavljali se sve do povratka kući.', 'petar.jpeg', 'kultura', 1),
(23, '13.06.2024 15:15', 'Porazi Hrvata u Bratislavi', 'Dva hrvatska tenisača danas su nastupila na Challengeru u Bratislavi i obojica su upisala poraze.', 'Iskusniji kazahstanski tenisač slavio je sa 6:1, 6:4 nakon jednog sata i sedam minuta provedenih na terenu. Zanimljivo, Dodig je proteklog tjedna upravo preko Popka izborio polufinale zagrebačkog Challengera, a tada je slavio u tri seta.\r\n\r\nU sljedećem kolu kazahstanski tenisač igrat će protiv poljskog predstavnika Kamila Majchrzaka koji je danas došao do pobjede protiv drugog hrvatskog predstavnika u Bratislavi, Luke Mikruta.\r\n\r\nMajchrzak je isto slavio u dva seta gotovo istim rezultatom. Bio je bolji sa 6:0, 6:4 nakon jednog sata i dvije minute provedene na terenu u njihovom prvom međusobnom dvoboju.\r\n\r\nPobjedu je upisao Nikola Mektić u paru s Weslyjem Koolhofom u četvrtfinalu ATP turnira koji se ovog tjedna igra u Hertogenboschu. Za protivnike su imali kolumbijsko-portugalsku kombinaciju Nicolas Barrientos/Francisco Cabral s kojima se ranije nisu susretali.\r\n\r\nKoolhof i Mektić izgubili su prvi set sa 7:5, ali su napravili preokret. Drugi su dobili sa 6:2, a treći u produženom tie-breaku s 10:5. Za finale će igrati protiv Maxa Purcella i Jordana Thompsona. test', 'tenis.jpg', 'sport', 0),
(24, '13.06.2024 15:16', 'WNBA: Washington bez pobjede', 'U sjeni velikog NBA finala odigrane su noćas i dvije utakmice WNBA lige.', 'U noći s četvrtka na petak odigrane su dvije utakmice WNBA lige, a u obje su slavile gošće. Chicago Sky, nakon dva poraza, vratio se pobjedama protiv Washington Mysticsa sa 79:71, a New York Liberty je petu uzastopnu pobjedu ostvario kod Atlante, završilo je 78:61.\r\n\r\nIgraj na utakmice WNBA lige na SuperSport.hr (18+ Igraj odgovorno)\r\n\r\n“Jubilarni“ deseti poraz ostvarile su noćas košarkašice Washingtona. Do sad su nekoliko puta bile blizu pobjedi i u ovom su susretu većinu vremena bile u vodstvu, ali ponovno je presudila loša završnica. Domaća ekipa prokockala je 13 poena prednosti, Chicago je u trećoj četvrtini napravio seriju 16:0 i nakon toga mirno priveo utakmicu kraju.\r\n\r\nAaliyah Edwards odigrala je odličnu utakmicu za poraženu ekipu, ali 23 poena i 14 skokova nije bilo dovoljno za prvu pobjedu sezone. Chennedy Carter bila je s 25 poena najefikasnija kod Chicaga, a Angel Reese upisala je double-double učinak sa 16 poena i 11 skokova.\r\n\r\nLiberty je na omjeru 9-2. Nakon starta u sezonu s četiri pobjede, košarkašice New Yorka upisale su dva vezana poraza, a na njih su odgovorile s pet uzastopnih slavlja. Atlanta je imala vodstvo u prvoj četvrtini, ali nakon toga sve je bilo u znaku gošći koje su utakmicu završile s najvećom prednošću od 17 razlike, 78:61.\r\n\r\nBreanna Stewart postigla je 25 poena, a njima je dodala deset skokova i pet asistencija. Ivana Dojkić propustila je prošlu utakmicu, a u ovoj je na parketu provela pet minuta. Promašila je svoj jedini šut i ostala bez učinka. Kod Atlante Allisha Gray ubacila je 16 koševa.', 'wnba.jpg', 'sport', 0),
(25, '13.06.2024 15:18', 'Hodak ostaje u Hajduku', 'Hajduk je objavio vijest o produženju ugovora s mladim desnim bekom Lukom Hodakom. ', 'Luka je prošao sve kategorije naše Akademije, a u prošloj sezoni standardno je igrao za juniorsku ekipu kao ulazni junior. Imao je zapaženu ulogu na poziciji desnog bočnog, a pozvan je i u U-19 reprezentaciju kao godinu dana mlađi igrač te je standardno igrao u toj konkurenciji. Posjeduje vrlo dobre do odlične tehničke elemente, taktički je jako zreo i odgovoran s vrlo dobrom anticipacijom igre. Polivalentan je igrač koji jednako dobro može odigrati na pozicijama defenzivnog veznog i desnog bočnog. Pokazuje iznimno zalaganje kako u utakmicama, tako i kroz treninge\", istaknuo je ovom prilikom sportski direktor Nikola Kalinić.\r\n\r\nVoditelj Hajdukove Akademije, Goran Sablić, ovako je opisao mladog desnog bočnog:\r\n\r\n\"Radi se o tehnički vrlo potkovanom igraču kojeg krasi izuzetno kvalitetan prvi dodir i kratko dodavanje. Taktički odlično razumije igru te posjeduje zavidan nivo osjećaja i smisla za suradnju. Jako dobro bira rješenja pod pritiskom te je vrlo racionalan i efikasan u igri. Kondicijski pokazuje visoke aerobne i anaerobne kapacitete uz visoku agilnost. Psihološki je jako motiviran, fokusiran i željan dokazivanja.\"\r\n\r\nVeliki je ovo dan i za Luku Hodaka čija karijera ide uzlaznom putanjom.\r\n\r\n\"Osjećaj je predivan, kad provedeš toliko godina u ovom Klubu, ovo je jedna dodatna motivacija za mene. Zahvalio bi se svim trenerima koji su me trenirali u Hajduku i Mosoru te obitelji koja mi je uvijek davala dodatnu snagu kad je bilo najteže. Protekli period u ovoj sezoni je bio odličan za mene, u Klubu i reprezentaciji igrao sam u starijem uzrastu, a tu su mi puno pomogli suigrači koji su me ohrabrivali i pomagali mi da budem najbolji što mogu. Cijela sezona je bila odlična za mene, posebno je dobar osjećaj bio naći se na klupi prve momčadi na gostovanju u Puli. Na meni je sada da opravdam povjerenje koje mi je Klub dao\", istaknuo je nakon potpisa ugovora. ', 'hodak.jpg', 'sport', 0),
(26, '13.06.2024 15:48', 'Mandić najbolji vratar Europe', 'Mladi vratar na sebe je privukao pažnju sjajnim izvedbama na golu hrvatskog prvaka...', 'Ovaj sjajni 22-godišnjak, dakako i najmlađi od svih nominiranih vratara, našao se u biranom društvu: Andreasa Wolffa (Industria Kielce), Sergeya Hernandeza (SC Magdeburg), Niklasa Landina (Aalborg Handbold), Emila Nielsena (Barça), Andreasa Palicke (Paris Saint-Germain Handball) i Gonzala Pereza de Vargasa (Barça).\r\n\r\n\"Ovo je veliko priznanje za mene i za dobru sezonu svih nas u rukometnom klubu Zagreb. Iskreno, nisam očekivao ovo i malo me je iznenadilo. Ipak sam ja vrlo mlad golman i biti u ovako biranom društvu najboljih svjetskih čuvara mreže iznimna je čast i poticaj za daljnji rad. Sretan sam, ponosan i tek sada polako postajem svjestan što sam napravio ove sezone u dresu Zagreba i reprezentacije. Dati ću sve od sebe da nastavim s dobrim partijama kako u klubu, tako i u reprezentaciji. Sljedeći cilj je napraviti rezultat na Olimpijskim igrama u najdražem dresu, a nakon toga u istom ritmu nastaviti braniti za Zagreb\", poručio je sjajni Matej Mandić.\r\n\r\nGlasovanje za izbor najbolje sedmorke i obrambenog specijalista trajat će do nedjelje, 23. lipnja a u njemu će sudjelovati igrači, treneri, novinari i navijači (svaka grupa nosi težinu od 25 posto glasova). Za Mateja Mandića može se glasovati putem mobilne aplikacije.', 'mandic.png', 'sport', 0),
(27, '13.06.2024 15:50', 'Neočekivan poraz Donne Vekić', 'Donna Vekić rano se oprostila od turnira u Hertogenboschu. Već u drugom kolu poražena je od Belgijke', 'Osmina finala turnira u Hertogenboschu Donni Vekić donijela je 85. igračicu svijeta Greet Minnen, ali Vekić nije opravdala status favoritkinje i upisala je poraz.\r\n\r\nIgraj na mečeve u Hertogenboschu na SuperSport.hr (18+ Igraj odgovorno)\r\n\r\nVrlo loše otvaranje meča, lako izgubljen prvi set, pa uvjerljivo osvojen drugi, ali Vekić nije zadržala tu razinu igre i pala je u trećem setu.\r\n\r\nU meč je ušla vrlo loše, Minnen je krenula s 5:0 i lakoćom je sa 6:1 uzela prvi set.\r\n\r\nNo pravi odgovor slijedi u drugom setu. Sada Vekić podiže razinu svoje igre, ne dopušta Belgijki niti gem te sa 6:0 poravnava na 1-1 u setovima.\r\n\r\nOdluka je pala u trećem setu gdje je Minnen rano došla do break, Vekić se vratila kod 5:4, ali odmah je izgubila servis i ujedno i meč.\r\n\r\nDonna se tako oprostila od turnira ranije od očekivanja i morala je stisnuti ruku boljoj protivnici u ovom meču.', 'donna.jpg', 'sport', 1),
(28, '13.06.2024 15:52', 'A. Ćosić odradila 100. emisiju', 'Simpatična Antonia uči iz dana u dan, a njezina struka bitno joj je pomogla u poslu.', 'Magistra psihologije i mlada snaga HRT-a, voditeljica i novinarka emisije \"Vijesti iz kulture\", Antonia Ćosić, u nedjelju je odradila svoju stotu emisiju otkako je stigla na javnu televiziju u voditeljskoj ulozi. Prije toga je radila na Radio Sljemenu, a posljednji posao bio joj je vezan uz odnose s javnošću ministra zdravstva Vilija Beroša. U intervjuu se osvrnula na svoj rad u proteklih desetak mjeseci, kako se nosi s pritiskom i od koga je najviše naučila obzirom da svakoga dana radi s brojnim kolegama. Psihologiju, kaže, koja joj je primarna struka, često koristi u poslu, a upravo je ona zaslužna za to da se odlično nosi sa svakodnevnim stresom.', 'anitonija.jpg', 'kultura', 0),
(29, '13.06.2024 15:54', 'Dobitnici Zlatne palme', 'Predsjednik Republike Zoran Milanović primio je Nebojšu Slijepčevića i Silvia Mumelaša.', 'Zlatnu palmu film \"Čovjek koji nije mogao šutjeti\" osvojio je na ovogodišnjem 77. Filmskom festivalu u Cannesu u kategoriji kratkometražnog filma.\r\n\r\nRiječ je o prvom hrvatskom filmu od osamostaljenja koji je osvojio tu prestižnu filmsku nagradu i tek drugom koji je bio u konkurenciji za njezino osvajanje.', 'zlatna-palma.jpg', 'kultura', 0),
(30, '13.06.2024 15:57', '5 najboljih filmova iz 2023.', 'Popis dobrih filmova iz 2023. koji čudom nisu nominirani za Oskara.', 'OSCAROM nagrađeni filmovi, naročito oni namjenski snimljeni kako bi upecali ovu prestižnu statuu, nikad mi se nisu posebno sviđali. To je, naravno, moj stav, ali iz višegodišnjeg iskustva razmjene dojmova, mišljenja i preporuka s brojnim prijateljima, kako filmofilima, tako i onima za sedmu umjetnost tek usputno zainteresiranima, shvatio sam da su oni koji dijele tu odbojnost prema Akademijinim laureatima daleko brojniji od onih koji svoj filmski ukus vode baš prema njima.\r\n\r\nKorpus preskočenih, nenagrađenih i ponajviše onih koje Akademija uopće nije ni vidjela ni uzimala u obzir oduvijek je bio daleko zanimljiviji. Dovoljno je proći povijesnu listu pobjednika i nominiranih, a onda je usporediti s prosječnom/općom listom filmova iz te godine i bit će jasno o čemu se govori. Uzmimo recimo 1989. – tada je Akademija odlučila da je Driving Miss Daisy najbolji film.\r\n\r\nI super, sjećam se da sam ga i sam gledao kao dijete… I to je sve, više mu se nikad nisam vratio. S druge strane, te iste godine izašao je Indiana Jones and the Last Crusade, film koji, poput mnogih, obožavam i znam napamet. Drugi dio Smrtonosnog oružja i drugi dio Povratka u budućnost natjerali su nas da izližemo VHS trake od puštanja, dok je, recimo, u nešto drukčijem ključu jedan od najboljih filmova godine bio Crimes and Misdemeanors Woodyja Alena, a, eto, nije bio ni nominiran.\r\n\r\nMy Left Foot, Dead Poets Society i Born on Fourth of July također su bolji filmovi od pobjednika i našli su se u konkurenciji, ali su meni opet filmovi poput Abyssa ili Pet Cemeteryja bili više u fokusu i ostali dublje u srcu. \r\n\r\nI tako bismo mogli nabrajati filmove iz svake godine. Naravno, ponekad se ono vrednije, makar iz američke produkcije, ipak nađe u izboru, ali, ponavljam, u većini slučajeva preostala hrpa krije daleko veći kultni potencijal i obično bude gledanija, voljenija i trajnija.\r\n\r\nJe li tako i ove godine? Vjerojatno jest. Sa svoje strane to ne mogu reći sa sigurnošću jer još nisam pogledao baš sve važno što se u Americi i ostatku svijeta snimilo, ali već imam listu od nekoliko bisera koji su me se iz različitih razloga dojmili daleko više nego sve ono što se u noći 11. ožujka našlo u Akademijinom izboru.\r\n\r\nListu dijelim s vama.', 'filmovi.jpg', 'kultura', 0),
(31, '13.06.2024 16:00', 'Bulić snimio navijačku pjesmu', 'Uoči Europskog prvenstva objavljen je velik broj navijačkih pjesama, a sad smo dobili još jednu', '\"Ovaj Bullhit je nastao, to jest ideja, već za vrijeme Eurosonga, zato što se iskristaliziralo \'Dream Team, zabij im\' kao super zamjena za Rim Tim Tagi Dim. Osim toga, pjesma je ujedinila Hrvatsku baš kao što to čini i naša repka. Kontaktirao sam Baby Lasagnu kojem se ideja svidjela.\r\n\r\nNjegova pjesma je odlična, naši nogometaši su odlični, a Bullhit je nastao kao dobitna kombinacija. Nadam se da će donijeti lijepe osjećaje svima koji navijaju i da će još više potaknuti euforiju koja je već prisutna posvuda. Za dalje ćemo vidjeti, ovisno o tome kako će se razvijati situacija u Njemačkoj, tako će se dalje razvijati i Bullhitovi. To više nije na nama, nego na našim dečkima, ali vjerujemo da će ih biti još puno\", rekao je Luka.', 'bulic.jpg', 'kultura', 0),
(32, '13.06.2024 16:03', 'Rakitić u Hajduku?', 'Hajduk dovodi i Ivana Rakitića?! Doznajemo koja je istina o ovom transferu', 'Dugo je trajalo zatišje na Poljudu. Čekao se trener, čekala su se pojačanja... Ali ništa se nije događalo. Tjedni su samo prolazili... Iako sezona još nije ni krenula, oblak pesimizma nadvio se nad glavama navijača Hajduka.', 'rakitic.jpeg', 'sport', 0),
(33, '13.06.2024 17:08', 'Ana Taylor-Joy u ulozi Furiosa', 'Furiosa: A Mad Max Saga s Cannesa je\r\nnapokon stigao i u naša kina', 'Trenutno traje Filmski festival u Cannesu, najprestižniji filmski festival na svijetu. Mnogi filmovi koje jedva čekamo imat će tamo svoju premijeru, a prvi dan je započeo s uvijek lijepim odjevnim kombinacijama kao i fokusom na žene. Naime, Greta Gerwig postala je prva američka redateljica koja je predsjednica žirija, a pridružuje joj se i Lily Gladstone. No, idemo mi na filmove. Jedan od prvih filmova koji je imao premijeru u Cannesu je apokaliptični film Furiosa: A Mad Max Saga i ako je suditi po reakcijama publike, bit će hit.\r\n\r\n\r\nPrvi Mad Max film izašao je davne 1979. kada je Maxa glumio Mel Gibson. Film je pratio policajca u postapokaliptičnoj Australiji koji se nakon određenih događaja ide osvetiti motociklističkoj bandi. Uslijedila su još dva nastavka s Gibsonom u glavnoj ulozi, no ponovni interes za lika vratio se 2015. kada je izašao izvrsni kino hit Mad Max: Fury Road u kojem je Maxa glumio Tom Hardy. Film je osvojio nekoliko tehničkih Oscara, a lik Furiose prvi put se pojavljuje u tom filmu. Tada ju je glumila Charlize Theron, a u prequelu koji nam dolazi gledat ćemo njezin origin story i kako se udružila s Maxom.', 'furiossa.png', 'kultura', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `korisnik`
--
ALTER TABLE `korisnik`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `korisnicko_ime` (`korisnicko_ime`);

--
-- Indexes for table `vijesti`
--
ALTER TABLE `vijesti`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `korisnik`
--
ALTER TABLE `korisnik`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `vijesti`
--
ALTER TABLE `vijesti`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
